dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install codecov
script:
  - coverage run --source flowutils --omit="flowutils/tests/*" run_tests.py

after_success:
  - codecov